# build
FROM node:18 as react-build
WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build

# production
FROM nginx:latest
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 80
