# build
FROM node:20 as react-build
WORKDIR /app
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm install

COPY . ./
RUN npm run build

# production
FROM nginx:latest
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 3001
