version: '3.7'
services:
    web:
        container_name: letters-game
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
            - ./deployment/nginx/:/etc/nginx/conf.d
        environment:
            - NODE_ENV=production
        command: yarn start