version: '3.7'
services:
    web:
        container_name: letters-game
        build:
            context: .
            dockerfile: Dockerfile-prod
        ports:
            - "3001:80"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=production