# build
FROM node:latest as react-build
WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build

# production
FROM nginx:latest
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 